# Generated by Django 2.2.2 on 2019-06-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='naame',
            new_name='name',
        ),
    ]
